---
version: '3.3'
services:
  groonga:
    build: ./groonga
    container_name: groonga_dev
    ports:
      - "10041:10041"
    volumes:
      - /var/groongadata:/mnt/db
    privileged: true
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

